Add more failure handling to goclone

diff --git a/goclone b/goclone
--- a/goclone
+++ b/goclone
@@ -13,13 +13,18 @@ if [ $# -lt 1 ] ; then
   exit 1
 fi 
 
-project=`echo $1 | cut -f2 -d"/"`
 group=`echo $1 | cut -f1 -d"/"`
+project=`echo $1 | cut -f2 -d"/"`
+
+if [ -z "$project" ] || [ -z  "$group" ] ; then
+  echo "Usage: clm group/project"
+  exit 1
+fi
 
 repo=$1
 target=$GOPATH/src/$repository/$group
 
-if [ -d $target ]; then
+if [ ! -d $target ] ; then
   mkdir -p $target 
 
   echo "Created folder "$target
@@ -27,7 +32,14 @@ fi
 
 cd $target
 
-git clone git@$repository:$1.git
+git clone git@$repository:$repo.git
+
+if [ $? -ne 0 ] ; then
+  echo "Could not clone repository"
+  exit 1
+fi
+
+symlink=$project 
 
 cd $GOPATH
-ln -s $target _$project
+ln -s $target/$project _$symlink
